name: headless_tokens
description: Headless tokens package (raw + semantic). Pure Dart.
version: 0.0.0
publish_to: none

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  meta: ^1.11.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.0

